import {
  AuthStepPayload,
  AuthStepResponse
} from '@modules/auth/auth-steps/entities/auth-steps.interface';

export type ForgotPasswordPayload = AuthStepPayload;
export type ForgotPasswordResponse = AuthStepResponse;

export enum StepForgotPasswordType {
  FILL_USER_ID = 'CHA01',
  USER_MUST_BE_SENT_TO_OFFICE = 'CHA02',
  USER_DOES_NOT_EXISTS = 'CHA03',
  USER_DOES_NOT_HAVE_SECURE_DATA = 'CHA04',
  RETRIES_LIMIT_EXCEED_ON_SECURE_DATA_SUBMIT = 'CHA05',
  FILL_SECURE_DATA = 'CHA06',
  CANNOT_GENERATE_SECURE_DATA = 'CHA07',
  REQUEST_INPUT_OTP_FROM_ANOTHER_CHANNEL = 'CHA08',
  RETRIES_LIMIT_EXCEED_ON_OTP_GENERATION_VALIDATION = 'CHA09',
  REQUEST_PRODUCT_VALIDATION = 'CHA10',
  FILL_OTP_DATA = 'CHA11',
  FILL_NEW_UNIVERSAL_PASSWORD = 'CHA12',
  CANNOT_REGISTER_DEVICE = 'CHA13',
  COMPLETED = 'CHA14',
  INACTIVE_CHANNEL = 'CHA15',
  CONFIRM_USER_PERMISSIONS = 'CHA16',
  SELECT_PRODUCT_TYPE = 'CHA17',
  CONFIRM_PROCESS_START = 'CHA18',
  SERVICE_ERROR = 'SERVICE ERROR'
}

export enum StepForgotPasswordTypeWithBiometrics {
  FILL_USER_ID = 'ENR01',
  USER_MUST_BE_SENT_TO_OFFICE = 'ENR02',
  USER_DOES_NOT_EXISTS = 'ENR03',
  USER_DOES_NOT_HAVE_SECURE_DATA = 'ENR04',
  RETRIES_LIMIT_EXCEED_ON_SECURE_DATA_SUBMIT = 'CHA05',
  FILL_SECURE_DATA = 'CHA06',
  CONFIRM_DEVICE_REGISTRATION = 'ENR06',
  CANNOT_GENERATE_SECURE_DATA = 'ENR09',
  REQUEST_INPUT_OTP_FROM_ANOTHER_CHANNEL = 'ENR10',
  RETRIES_LIMIT_EXCEED_ON_OTP_GENERATION_VALIDATION = 'ENR11',
  REQUEST_PRODUCT_VALIDATION = 'CHA10',
  FILL_OTP_DATA = 'ENR13',
  FILL_NEW_UNIVERSAL_PASSWORD = 'ENR14',
  CANNOT_REGISTER_DEVICE = 'ENR15',
  COMPLETED = 'ENR17',
  INACTIVE_CHANNEL = 'ENR18',
  CONFIRM_USER_PERMISSIONS = 'ENR21',
  SELECT_PRODUCT_TYPE = 'CHA17',
  CONFIRM_PROCESS_START = 'ENR26',
  SERVICE_ERROR = 'SERVICE ERROR',
  BIOMETRIC_VERIFICATION = 'ENR25',
  ONESPAN_ACTIVATE_INSTANCE = 'ENR19',
  ONESPAN_ACTIVATE_LICENSE = 'ENR20'
}
