import {
  ProductBodyType,
  TypeProduct
} from '@commons/entities/product/balance.interface';
import { ProductStyleType } from '@modules/product/entities/product.interface';
import { ProductTypeDetail } from '@commons/entities/product/product-type-detail.interface';
import { ProductSpiUserKey } from '@app/modules/product/entities/product-spi-user-key';

export interface Product {
  type?: string;
  typeName?: string;
  cardType?: string;
  franchise?: string;
  accountType?: number | string;
  numberProduct?: string;
  balance?: number;
  description?: string;
  availableBalance?: number;
  balanceTypeProduct?: number;
  blockedBalance?: number;
  inProjects?: number;
  pendingBalance?: number;
  portfolios?: any[];
  govIssueIdentType?: string;
  key?: string;
  cashFlowInfo?: {
    startDate: string;
    endDate: string;
    incomingMoney: number;
    outgoingMoney: number;
  };
  availablePurchasesBalance?: number;
  availableAdvanceBalance?: number;
  availableBalanceWithOverdraft?: number;
  expense?: number;
  creditLimit?: number;
  cutDate?: string;
  dueDate?: string;
  nextPayment?: string;
  effectiveRate?: string;
  openDate?: string;
  expirationDate?: string;
  term?: string;
  pactedEffectiveRate?: string;
  liquidationMethod?: string;
  startupValue?: number;
  earnedInterest?: number;
  minimumPayment?: number;
  minimumPaymentReduced?: number;
  fontRetention?: number;
  demandableValue?: number;
  outcomes?: number;
  inPockets?: number;
  availableBarPercentage?: number;
  availableHomePurchase?: number;
  yields?: number;
  freeDestinationBalance?: number;
  withholding?: number;
  notEmpty?: boolean;
  others?: number;
  id?: string;
  idUM?: string;
  bankCode?: string;
  totalDue?: string;
  deliveryDate?: string;
  dueDays?: number;
  dueAmount?: number;
  nextInstallment?: number;
  nextInstallmentDate?: string;
  overdraftApprovedQuota?: string;
  balanceForOrdering?: number;
  availableOverdraft?: string;
  forPayment?: number;
  productBodyType?: ProductBodyType;
  bodyAvailableBalance?: number;
  bodyFirstText?: string;
  bodyFirstValue?: number;
  bodySecondText?: string;
  bodySecondValue?: number;
  productAction?: string;
  interest?: number;
  backUrl?: string;
  style?: ProductStyleType;
  nickname?: string;
  avalTagKey?: ProductSpiUserKey[];
  breBUserKeys?: ProductSpiUserKey[];
  relativeId?: string;
  name?: string;
  numberDigitalCard?: string;
  numberProductParent?: string;
  acctTypeParent?: string;
  isNew?: boolean;
  productTypeDetailKey?: ProductTypeDetail;
  productTypeDetailValue?: string;
  currency?: string;
  trmDay?: number;
  availableQuotaDollars?: number;
  minimumPaymentDollars?: number;
  payDayLimitDollars?: string;
  fullPaymentDollars?: number;
  expenseDollars?: number;
  typeProduct?: TypeProduct;
}
