export enum DesignioInputType {
  Text = 'text',
  Password = 'password',
  Email = 'email',
  Search = 'search',
  Tel = 'tel',
  Url = 'url',
  Number = 'number',
  Range = 'range',
  Date = 'date',
  Month = 'month',
  Week = 'week',
  Time = 'time',
  DateTimeLocal = 'datetime-local',
  Submit = 'submit',
  Reset = 'reset',
  Button = 'button',
  Image = 'image',
  Checkbox = 'checkbox',
  Radio = 'radio',
  File = 'file',
  Color = 'color',
  Hidden = 'hidden'
}
