sonar.sourceEncoding=UTF-8
sonar.sources=packages/stencil
sonar.exclusions=**/node_modules/**, **/*.d.ts, **/*.config.ts, packages/stencil/src/components/mocks/**, packages/stencil/src/index.ts, packages/stencil/src/assets/**/*
sonar.tests=packages/stencil
sonar.test.inclusions=**/*.spec.ts, **/*.spec.tsx
sonar.javascript.lcov.reportPaths=packages/stencil/coverage/lcov.info
