sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.projectKey=ma:bavv-mb-frontend-app
sonar.projectName=bavv-mb-frontend-app
sonar.projectVersion=4.8.3
sonar.host.url=http://localhost:9000
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tslintconfigpath=tslint.json
sonar.inclusions=/src/app/**.ts
sonar.test.inclusions=/src/app/**.spec.ts
sonar.exclusions=/src/polyfills.ts, /src/app/app-preload-strategy.ts, **/fill-otp-data.component.ts, **/feature-toggle.service.ts, **/qr.service.ts, **/scanner.service.ts, **/barcode-scanner.service.ts, **/barcode-scanner.component.ts, **/wallet-sdk.service.ts, **/product-action-tour.component.ts, **/notifications-menu.component.ts, **/forgot-password-strategy.factory.ts, /src/app/app.routing.ts, /src/app/app.translate.ts, **/test-helpers/**, **/assets/**, **/store/**, **/effects/**, **/e2e/**, **/**.module.ts, **/directives/**, **/utils/**, **/interceptors/**, **/capacitor-web-plugins/**, **/**.helper.ts, **/**.helpers.ts, **/**.mapper.ts, **/**.interface.ts, **/**.resolver.ts, **/**.constants.ts, **/*.entities.ts, **/**.facade.ts, **/*.action.ts, **/*.selector.ts, **/*.state.ts, **/*.base.ts, **/*.guard.ts, **/*.animation.ts, **/*.strategy.ts, **/*.mock.ts
