/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SIZE_BUTTON as SIZE_BUTTON_BPOP, VARIANT_BUTTON, WIDTH_MODE as WIDTH_MODE_BPOP } from "./commons/button-bpop.interface";
import { BdoButtonStandard, BdoButtonType } from "./commons/button-bocc.interface";
import { SIZE_BUTTON, WIDTH_MODE } from "./commons/button-bavv.interface";
import { PaddingForCard } from "./components/designio-card/card-bavv.interface";
import { SizeDropDown, StateDropDown } from "@avaldigitallabs/adl-commons-design-system-frontend-bpop-designio/dist/types/commons/models/molecules/bpop-designio-dropdown.interfaces";
import { FooterDesignioVariant } from "./components/designio-footer/designio-footer.enum";
import { DesignioInputType } from "./components/designio-input/designio-input-type.enum";
import { Input as BoccInput, FIELD_STATUS } from "@avaldigitallabs/adl-commons-design-system-frontend-bocc-designio/dist/loader";
import { RadioButtonAttributes, RadioButtonChangeDetail } from "./components/designio-radio-button/designio-radio-button";
export { SIZE_BUTTON as SIZE_BUTTON_BPOP, VARIANT_BUTTON, WIDTH_MODE as WIDTH_MODE_BPOP } from "./commons/button-bpop.interface";
export { BdoButtonStandard, BdoButtonType } from "./commons/button-bocc.interface";
export { SIZE_BUTTON, WIDTH_MODE } from "./commons/button-bavv.interface";
export { PaddingForCard } from "./components/designio-card/card-bavv.interface";
export { SizeDropDown, StateDropDown } from "@avaldigitallabs/adl-commons-design-system-frontend-bpop-designio/dist/types/commons/models/molecules/bpop-designio-dropdown.interfaces";
export { FooterDesignioVariant } from "./components/designio-footer/designio-footer.enum";
export { DesignioInputType } from "./components/designio-input/designio-input-type.enum";
export { Input as BoccInput, FIELD_STATUS } from "@avaldigitallabs/adl-commons-design-system-frontend-bocc-designio/dist/loader";
export { RadioButtonAttributes, RadioButtonChangeDetail } from "./components/designio-radio-button/designio-radio-button";
export namespace Components {
    interface DesignioBadge {
        /**
          * Clases CSS adicionales (BOCC)
         */
        "classNames"?: string;
        /**
          * Identificador único para el badge/subcomponente
         */
        "idBadge"?: string;
        /**
          * Modo sólido (BBOG)
         */
        "isSolid"?: boolean;
        /**
          * Forma cuadrada (BOCC). Para BAVV use shape.
         */
        "isSquare"?: boolean;
        /**
          * Visibilidad del badge (BOCC). Si es false, no se muestra.
         */
        "isVisible"?: boolean;
        /**
          * Texto del badge (si no se usa el slot)
         */
        "label"?: string;
        /**
          * Ícono de prefijo (soportado en bpop y bocc)
         */
        "prefixIcon"?: string;
        /**
          * Muestra botón de cierre (BBOG)
         */
        "removeTag"?: boolean;
        /**
          * Forma del borde (BAVV)
         */
        "shape"?: string;
        /**
          * Tamaño del badge (valores dependen del banco)
         */
        "size"?: string;
        /**
          * Ícono de sufijo (soportado en bpop)
         */
        "suffixIcon"?: string;
        /**
          * Tipo/entidad del badge que determina el adapter a renderizar
          * @default 'bbog'
         */
        "type": 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * Variante visual (mapeada por banco)
         */
        "variant"?: string;
    }
    interface DesignioButton {
        /**
          * The type of the button (for BAVV). BUTTON, SUBMIT, RESET.
          * @default 'submit'
         */
        "buttonType": 'button' | 'submit' | 'reset';
        /**
          * Custom height for the button (for BAVV).
         */
        "customHeight"?: string;
        /**
          * Custom width for the button (for BAVV).
         */
        "customWidth"?: string;
        /**
          * Enable divider between text and suffix icon for BOCC
          * @default false
         */
        "dividedBocc": boolean;
        /**
          * The html index of the button (for BAVV).
          * @default 0
         */
        "htmlIndex": number;
        /**
          * Id of button
         */
        "idButton"?: string;
        /**
          * State of button is Disabled true or false
          * @default false
         */
        "isDisabled": boolean;
        /**
          * State of button is Loading true or false
          * @default false
         */
        "isLoading": boolean;
        /**
          * Name or description of button
          * @default ''
         */
        "label": string;
        /**
          * The name of the button (for BAVV).
         */
        "name"?: string;
        /**
          * Prop for load icon before name in button
         */
        "prefixIcon"?: string;
        /**
          * The size of the button (for BAVV). SMALL, REGULAR.
          * @default SIZE_BUTTON.REGULAR
         */
        "sizeBavv": SIZE_BUTTON;
        /**
          * Size for BOCC button (L, M, S)
          * @default 'M'
         */
        "sizeBocc": 'L' | 'M' | 'S';
        /**
          * Size for BPOP button
          * @default SIZE_BUTTON_BPOP.REGULAR
         */
        "sizeBpop": SIZE_BUTTON_BPOP;
        /**
          * Prop for load icon after name in button
         */
        "suffixIcon"?: string;
        /**
          * Type or entity form button
          * @default 'bbog'
         */
        "type": 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * Prop variant for bavv-design-button
          * @default 'primary'
         */
        "variantBavv": 'primary' | 'secondary' | 'tertiary' | 'borderless';
        /**
          * Type/variant for BOCC button - usando BdoButtonType correcto
          * @default 'primary'
         */
        "variantBocc": BdoButtonType;
        /**
          * Prop variant for bpop-design-button
          * @default VARIANT_BUTTON.PRIMARY
         */
        "variantBpop": VARIANT_BUTTON;
        /**
          * The width mode of the button (for BAVV). DEFAULT, AUTO, FULL.
          * @default WIDTH_MODE.DEFAULT
         */
        "widthModeBavv": WIDTH_MODE;
        /**
          * Width mode for BPOP button
          * @default WIDTH_MODE_BPOP.DEFAULT
         */
        "widthModeBpop": WIDTH_MODE_BPOP;
    }
    interface DesignioCard {
        /**
          * Text body of card
         */
        "bodyText"?: string;
        /**
          * type of border for card (BOCC only)
          * @default 'default'
         */
        "borderType"?: | 'default'
    | 'info'
    | 'success'
    | 'darger';
        /**
          * height of card (Only for BBOG)
         */
        "boxHeight"?: string;
        /**
          * width of card (Only for BBOG)
         */
        "boxWidth"?: string;
        /**
          * Text used for button (Only for BBOG)
          * @default ''
         */
        "buttonText"?: string;
        /**
          * Text used for secondary button (Only for BBOG card notification)
         */
        "buttonTextSecondary"?: string;
        /**
          * define if it's button or link (Only for BBOG)
          * @default 'link'
         */
        "buttonType"?: 'link' | 'secondary';
        /**
          * Border contain card, if false it does not show (BAVV only)
          * @default false
         */
        "cardHasBorder": boolean;
        /**
          * Padding of component, it can have 3 values: 12 | 24 | 36 (BAVV only)
          * @default 12
         */
        "cardPadding": PaddingForCard;
        /**
          * Type of card for BBOG
          * @default 'access'
         */
        "cardType": 'access' | 'notification';
        /**
          * define color for text in avatar (Only for BBOG)
         */
        "colorTextAvatar"?: string;
        /**
          * enable footer of card (BOCC only)
          * @default false
         */
        "displayFooter"?: boolean;
        /**
          * enable header of card (BOCC only)
          * @default false
         */
        "displayHeader"?: boolean;
        /**
          * enable or disable component (Only for BBOG access) and used for badge in avatar (Only for BBOG notification)
         */
        "enable"?: boolean;
        /**
          * Text used for footer (only BOCC)
         */
        "footerText"?: string;
        /**
          * define if it's button or link for access card in true for button, in notification define if has two buttons (Only for BBOG)
          * @default false
         */
        "hasButtons"?: boolean;
        /**
          * Text used for header (only BOCC)
         */
        "headerText"?: string;
        /**
          * Id of card
         */
        "idCard"?: string;
        /**
          * id of footer (BOCC only)
         */
        "idFooter"?: string;
        /**
          * id of header (BOCC only)
         */
        "idHeader"?: string;
        /**
          * define tag solid or with border (Only for BBOG)
          * @default false
         */
        "isTagSolid"?: boolean;
        /**
          * Text secondary  of card (only BBOG)
         */
        "secondaryText"?: string;
        /**
          * Text used for tag (Only for BBOG)
         */
        "tagLabel"?: string;
        /**
          * text for avatar (Only for BBOG)
         */
        "textAvatar"?: string;
        /**
          * define title for card (Only for BBOG)
          * @default ''
         */
        "titleCard"?: string;
        /**
          * define title in one line or two (Only for BBOG)
         */
        "titleHasOneLine"?: boolean;
        /**
          * Type or entity form buttom
          * @default 'bocc'
         */
        "type": 'bocc' | 'bavv' | 'bbog' | 'bpop';
        /**
          * define avatar type (Only for BBOG)
          * @default 'icon'
         */
        "typeAvatar"?: 'text' | 'icon' | 'img';
        /**
          * define type icon (Only for BBOG)
         */
        "typeIcon"?: string;
        /**
          * Type of logo for access card (Only for BBOG)
         */
        "typeLogo"?: string;
        /**
          * define type for pictogram (Only for BBOG)
         */
        "typePicto"?: string;
        /**
          * define type tag (Only for BBOG)
         */
        "typeTag"?: string;
        /**
          * define state of card (Only for BBOG)
          * @default false
         */
        "unread"?: boolean;
        /**
          * link for image of avatar (Only for BBOG)
         */
        "urlImgAvatar"?: string;
        /**
          * options for card in bbog (Only for BBOG)
         */
        "userOptions"?: string;
    }
    interface DesignioDropdown {
        /**
          * Helper Text
         */
        "helperText"?: string;
        /**
          * Disabled dropdown
          * @default false
         */
        "isDisabled"?: boolean;
        /**
          * Text Help Bog
          * @default false
         */
        "isHelp"?: boolean;
        /**
          * Popup Mode mobile
          * @default false
         */
        "isPopUp"?: boolean;
        /**
          * Required
          * @default false
         */
        "isRequired"?: boolean;
        /**
          * Label dropdown
         */
        "label"?: string;
        /**
          * Options List
          * @default []
         */
        "options": any[];
        /**
          * Placeholder
         */
        "placeholder"?: string;
        /**
          * Size dropdown
         */
        "size"?: SizeDropDown;
        /**
          * State dropdown (error, warning, default, selected...)
         */
        "state"?: StateDropDown;
        /**
          * Tooltip enable (Bogotá only)
          * @default false
         */
        "tooltip"?: boolean;
        /**
          * Tooltip header text
         */
        "tooltipHeader"?: string;
        /**
          * Tooltip body text
         */
        "tooltipMessage"?: string;
        /**
          * Label dropdown
          * @default 'bbog'
         */
        "type": 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * Select Value
         */
        "value"?: string | number;
    }
    interface DesignioFooter {
        /**
          * additionalText
          * @default 'Texto adicional'
         */
        "additionalText": string;
        /**
          * Props BOCC
          * @default 'bdo-footer-company'
         */
        "elementId": string;
        /**
          * showAdditionalText
          * @default false
         */
        "showAdditionalText": boolean;
        /**
          * showFogafinLogo
          * @default false
         */
        "showFogafinLogo": boolean;
        /**
          * Bank footer
          * @default 'bocc'
         */
        "type": 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * Props commons
          * @default FooterDesignioVariant.DEFAULT
         */
        "variant": FooterDesignioVariant;
    }
    interface DesignioInput {
        /**
          * The autocomplete attribute.
          * @default 'off'
         */
        "autocomplete": string;
        /**
          * Optional button text to display on the right side of the input for BAVV.
          * @default ''
         */
        "bavvButtonText": string;
        /**
          * The icon name for the input of BAVV.
          * @default ''
         */
        "bavvIconName": string;
        /**
          * The icon position for the input of BAVV.
          * @default ''
         */
        "bavvIconPosition": 'left' | 'right' | '';
        /**
          * Autoselect of BBOG.
          * @default false
         */
        "bbogAutoSelect": boolean;
        /**
          * The decimal quantity of BBOG.
         */
        "bbogDecimalQuantity"?: number;
        /**
          * Email validation on blur of BBOG.
          * @default false
         */
        "bbogEmailValidationOnBlur": boolean;
        /**
          * Name of the icon to render of BBOG.
          * @default ''
         */
        "bbogIcon": string;
        /**
          * The interactive tooltip message of BBOG
         */
        "bbogInteractiveTooltipMessage"?: string;
        /**
          * Name of the left icon to render of BBOG.
         */
        "bbogLeftIcon"?: string;
        /**
          * Enables/Disables the hide password mode.
          * @default false
         */
        "bbogPasswordMode": boolean;
        /**
          * Enables/Disables the control of BBOG.
          * @default 'ENABLED'
         */
        "bbogStatus": string;
        /**
          * Show/Hide tooltip of BBOG.
          * @default false
         */
        "bbogTooltip": boolean;
        /**
          * The tooltip message of BBOG
         */
        "bbogTooltipMessage"?: string;
        /**
          * The tooltip position of BBOG
          * @default 'right'
         */
        "bbogTooltipPosition": string;
        /**
          * The tooltip title of BBOG
         */
        "bbogTooltipTitle"?: string;
        /**
          * View mode of BBOG.
          * @default false
         */
        "bbogViewMode": boolean;
        /**
          * The attributes of the input field of BOCC
         */
        "boccAttributes"?: BoccInput | string;
        /**
          * The field status of the input field of BOCC
         */
        "boccFieldStatus": FIELD_STATUS | string;
        /**
          * The maximum number of decimals allowed of BOCC
          * @default 0
         */
        "boccMaximumDecimalsAllowed": number;
        /**
          * The prefix text of the input field of BOCC
          * @default ''
         */
        "boccPrefixText": string;
        /**
          * IDs to describe via `aria-describedby` of BPOP.
          * @default ''
         */
        "bpopAriaDescribedBy": string;
        /**
          * Aria label for the input of BPOP.
          * @default ''
         */
        "bpopAriaLabelProp": string;
        /**
          * Input `autocapitalize` attribute of BPOP.
          * @default ''
         */
        "bpopAutocapitalizeProp": string;
        /**
          * Text of the embedded button (right side) of BPOP.
          * @default ''
         */
        "bpopButtonText": string;
        /**
          * Name of the icon to render of BPOP.
          * @default ''
         */
        "bpopIconName": string;
        /**
          * Icon position (`left`/`right`) of BPOP.
          * @default ''
         */
        "bpopIconPosition": 'left' | 'right' | '';
        /**
          * HTML `size` attribute of BPOP.
         */
        "bpopSize"?: number;
        /**
          * HTML `spellcheck` attribute of BPOP.
          * @default false
         */
        "bpopSpellcheckProp": boolean;
        /**
          * Step size (number/date) of BPOP.
         */
        "bpopStepSize"?: string | number;
        /**
          * `tabindex` to apply of BPOP.
         */
        "bpopTabIndexProp"?: number;
        /**
          * HTML `title` attribute of BPOP.
          * @default ''
         */
        "bpopTitleProp": string;
        /**
          * Whether the input is disabled for BAVV, BPOP or BOCC. It doesn't apply to BBOG. For BBOG please use the bbogStatus property
          * @default false
         */
        "disabled": boolean;
        /**
          * Entity for the input
          * @default 'bbog'
         */
        "entity": 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * The text shown as helper below the input for BAVV, BPOP or BBOG. It doesn't apply to BOCC.
         */
        "helper"?: string;
        /**
          * The ID attribute of the input.
          * @default ''
         */
        "idProp": string;
        /**
          * The input mode (e.g., numeric, text) for BAVV, BPOP or BOCC. It doesn't apply to BBOG.
         */
        "inputModeProp"?: string;
        /**
          * Label text displayed with the input field.
          * @default ''
         */
        "label": string;
        /**
          * The maximum value (for number/date inputs).
         */
        "max"?: string | number;
        /**
          * The maxlength attribute defining max number of characters.
         */
        "maxLength"?: number;
        /**
          * The minimum value (for number/date inputs).
         */
        "min"?: string | number;
        /**
          * The minlength attribute defining min number of characters.
         */
        "minLength"?: number;
        /**
          * The name attribute of the input.
          * @default ''
         */
        "name": string;
        /**
          * The pattern attribute for regex validation.
         */
        "pattern"?: string;
        /**
          * The placeholder text displayed when the input is empty.
          * @default ''
         */
        "placeholder": string;
        /**
          * Whether the input is readonly.
          * @default false
         */
        "readonly": boolean;
        /**
          * Whether the input is required.
          * @default false
         */
        "required": boolean;
        /**
          * The type of input (e.g., text, password, email, number, etc.).
          * @default DesignioInputType.Text
         */
        "type": DesignioInputType;
        /**
          * The value of the input.
          * @default ''
         */
        "value": string;
    }
    interface DesignioLoader {
        /**
          * Starts animation as soon as component is loaded (BBOG)
         */
        "autoPlay"?: boolean;
        /**
          * Displays a message when loader is open (BOCC)
         */
        "displayMessage"?: boolean;
        /**
          * External json file for animation (BBOG)
         */
        "fileAnimation"?: string;
        /**
          * Id for loader element (BBOG)
         */
        "idEl"?: string;
        /**
          * Variant for BAVV loader
         */
        "isMainSpinner"?: boolean;
        /**
          * Makes loader visible or hidden
         */
        "isopen"?: boolean;
        /**
          * Loader type (BBOG)
         */
        "loaderType"?: string;
        /**
          * Plays animation in a loop (BBOG)
         */
        "loop"?: boolean;
        /**
          * Main text for loader (BOCC, BAVV, BBOG, BPOP)
         */
        "mainText"?: string;
        /**
          * Secondary text for loader, if available (BOCC, BAVV)
         */
        "secondaryText"?: string;
        /**
          * Loader size (BPOP)
         */
        "size"?: | 'xsmall'
    | 'small'
    | 'medium'
    | 'large';
        /**
          * Type or entity form buttom
          * @default 'bbog'
         */
        "type": 'bocc' | 'bpop' | 'bavv' | 'bbog';
    }
    interface DesignioModal {
        /**
          * Title alignment.
          * @default 'center'
         */
        "alignTitle"?: 'left' | 'center' | 'right';
        /**
          * Closes the modal programmatically.
         */
        "closeModal": () => Promise<void>;
        /**
          * Custom CSS class for the modal.
         */
        "customClass"?: string;
        /**
          * Direction of the modal buttons.
          * @default 'vertical'
         */
        "direction"?: 'horizontal' | 'vertical';
        /**
          * Optional element id for the modal.
         */
        "elementId"?: string;
        /**
          * Hide close button in the modal.
          * @default false
         */
        "hideClose"?: boolean;
        /**
          * Icon name for the modal.
         */
        "icon"?: string;
        /**
          * Illustrated icon name for the modal.
         */
        "illustratedIcon"?: string;
        /**
          * Custom modal ID.
         */
        "modalId"?: string;
        /**
          * Title of the modal.
         */
        "modalTitle"?: string;
        /**
          * Opens the modal programmatically.
         */
        "openModal": () => Promise<void>;
        /**
          * Primary button configuration.
         */
        "primaryButtonConfig"?: BdoButtonStandard;
        /**
          * Secondary button configuration.
         */
        "secondaryButtonConfig"?: BdoButtonStandard;
        /**
          * Show close button in the modal.
          * @default false
         */
        "showClose"?: boolean;
        /**
          * Show primary button in the modal.
          * @default false
         */
        "showPrimaryButton"?: boolean;
        /**
          * Show secondary button in the modal.
          * @default false
         */
        "showSecondaryButton"?: boolean;
        /**
          * Size of the modal.
          * @default 'md'
         */
        "size"?: 'lg' | 'md' | 'sm';
        /**
          * Subtitle of the modal.
         */
        "subtitle"?: string;
        /**
          * Modal type to display.
          * @default 'bbog'
         */
        "type": 'bocc' | 'bpop' | 'bavv' | 'bbog';
    }
    interface DesignioRadioButton {
        /**
          * Allow unselecting the radio button.
          * @default false
         */
        "allowUnselect"?: boolean;
        /**
          * Whether the radio button is checked.
          * @default false
         */
        "checked": boolean;
        /**
          * Whether to wrap the radio in a container.
          * @default false
         */
        "container"?: boolean;
        /**
          * Custom attributes for the radio button.
         */
        "customAttributes"?: RadioButtonAttributes | string;
        /**
          * Whether the radio button is disabled.
          * @default false
         */
        "disabled": boolean;
        /**
          * Whether to invert the label position.
          * @default false
         */
        "invertLabel"?: boolean;
        /**
          * The label for the radio button.
         */
        "label"?: string;
        /**
          * The group name for the radio button.
         */
        "name": string;
        /**
          * The unique id for the radio button.
         */
        "radioId": string;
        /**
          * Show the label next to the radio button.
          * @default true
         */
        "showLabel": boolean;
        /**
          * The size of the radio button.
          * @default 'default'
         */
        "size"?: 'default' | 'large' | 'medium' | 'small';
        /**
          * The visual state of the radio button.
          * @default 'default'
         */
        "state"?: | 'default'
    | 'hover'
    | 'error'
    | 'info'
    | 'disabled'
    | 'checked';
        /**
          * The type of radio button (design system).
          * @default 'bpop'
         */
        "type": 'bpop' | 'bavv' | 'bbog' | 'bocc';
        /**
          * The value of the radio button.
         */
        "value"?: string;
    }
    interface MyComponent {
        /**
          * Name
         */
        "name": string;
    }
}
export interface DesignioBadgeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignioBadgeElement;
}
export interface DesignioButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignioButtonElement;
}
export interface DesignioCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignioCardElement;
}
export interface DesignioDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignioDropdownElement;
}
export interface DesignioInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignioInputElement;
}
export interface DesignioModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignioModalElement;
}
export interface DesignioRadioButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignioRadioButtonElement;
}
declare global {
    interface HTMLDesignioBadgeElementEventMap {
        "badgeClicked": {
    type: 'bocc' | 'bpop' | 'bavv' | 'bbog';
    id?: string;
    label?: string;
  };
    }
    interface HTMLDesignioBadgeElement extends Components.DesignioBadge, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignioBadgeElementEventMap>(type: K, listener: (this: HTMLDesignioBadgeElement, ev: DesignioBadgeCustomEvent<HTMLDesignioBadgeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignioBadgeElementEventMap>(type: K, listener: (this: HTMLDesignioBadgeElement, ev: DesignioBadgeCustomEvent<HTMLDesignioBadgeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignioBadgeElement: {
        prototype: HTMLDesignioBadgeElement;
        new (): HTMLDesignioBadgeElement;
    };
    interface HTMLDesignioButtonElementEventMap {
        "buttonClicked": {
    type: string;
    id?: string;
    label?: string;
    value?: any;
  };
    }
    interface HTMLDesignioButtonElement extends Components.DesignioButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignioButtonElementEventMap>(type: K, listener: (this: HTMLDesignioButtonElement, ev: DesignioButtonCustomEvent<HTMLDesignioButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignioButtonElementEventMap>(type: K, listener: (this: HTMLDesignioButtonElement, ev: DesignioButtonCustomEvent<HTMLDesignioButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignioButtonElement: {
        prototype: HTMLDesignioButtonElement;
        new (): HTMLDesignioButtonElement;
    };
    interface HTMLDesignioCardElementEventMap {
        "cardClicked": void;
        "linkClicked": void;
        "linkClickedSecond": void;
        "optionMenuClicked": void;
    }
    interface HTMLDesignioCardElement extends Components.DesignioCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignioCardElementEventMap>(type: K, listener: (this: HTMLDesignioCardElement, ev: DesignioCardCustomEvent<HTMLDesignioCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignioCardElementEventMap>(type: K, listener: (this: HTMLDesignioCardElement, ev: DesignioCardCustomEvent<HTMLDesignioCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignioCardElement: {
        prototype: HTMLDesignioCardElement;
        new (): HTMLDesignioCardElement;
    };
    interface HTMLDesignioDropdownElementEventMap {
        "designioSelectionChange": any;
    }
    interface HTMLDesignioDropdownElement extends Components.DesignioDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignioDropdownElementEventMap>(type: K, listener: (this: HTMLDesignioDropdownElement, ev: DesignioDropdownCustomEvent<HTMLDesignioDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignioDropdownElementEventMap>(type: K, listener: (this: HTMLDesignioDropdownElement, ev: DesignioDropdownCustomEvent<HTMLDesignioDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignioDropdownElement: {
        prototype: HTMLDesignioDropdownElement;
        new (): HTMLDesignioDropdownElement;
    };
    interface HTMLDesignioFooterElement extends Components.DesignioFooter, HTMLStencilElement {
    }
    var HTMLDesignioFooterElement: {
        prototype: HTMLDesignioFooterElement;
        new (): HTMLDesignioFooterElement;
    };
    interface HTMLDesignioInputElementEventMap {
        "bavvButtonClick": void;
        "bavvValueChange": void;
        "bavvInputChange": void;
        "bavvInputFocus": void;
        "bavvInputBlur": void;
        "bbogAtInputChanged": void;
        "bbogAtInputEnterKey": void;
        "bbogAtInputOnBlur": void;
        "bbogAtInputOnFocus": void;
        "bbogAtInputOnKeyDown": void;
        "bbogAtInputUpdated": void;
        "bbogOnInputIconClick": void;
    }
    interface HTMLDesignioInputElement extends Components.DesignioInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignioInputElementEventMap>(type: K, listener: (this: HTMLDesignioInputElement, ev: DesignioInputCustomEvent<HTMLDesignioInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignioInputElementEventMap>(type: K, listener: (this: HTMLDesignioInputElement, ev: DesignioInputCustomEvent<HTMLDesignioInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignioInputElement: {
        prototype: HTMLDesignioInputElement;
        new (): HTMLDesignioInputElement;
    };
    interface HTMLDesignioLoaderElement extends Components.DesignioLoader, HTMLStencilElement {
    }
    var HTMLDesignioLoaderElement: {
        prototype: HTMLDesignioLoaderElement;
        new (): HTMLDesignioLoaderElement;
    };
    interface HTMLDesignioModalElementEventMap {
        "opened": { type: string; modalId: string };
        "closed": { type: string; modalId: string };
    }
    interface HTMLDesignioModalElement extends Components.DesignioModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignioModalElementEventMap>(type: K, listener: (this: HTMLDesignioModalElement, ev: DesignioModalCustomEvent<HTMLDesignioModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignioModalElementEventMap>(type: K, listener: (this: HTMLDesignioModalElement, ev: DesignioModalCustomEvent<HTMLDesignioModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignioModalElement: {
        prototype: HTMLDesignioModalElement;
        new (): HTMLDesignioModalElement;
    };
    interface HTMLDesignioRadioButtonElementEventMap {
        "radioChange": RadioButtonChangeDetail;
    }
    interface HTMLDesignioRadioButtonElement extends Components.DesignioRadioButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignioRadioButtonElementEventMap>(type: K, listener: (this: HTMLDesignioRadioButtonElement, ev: DesignioRadioButtonCustomEvent<HTMLDesignioRadioButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignioRadioButtonElementEventMap>(type: K, listener: (this: HTMLDesignioRadioButtonElement, ev: DesignioRadioButtonCustomEvent<HTMLDesignioRadioButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignioRadioButtonElement: {
        prototype: HTMLDesignioRadioButtonElement;
        new (): HTMLDesignioRadioButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "designio-badge": HTMLDesignioBadgeElement;
        "designio-button": HTMLDesignioButtonElement;
        "designio-card": HTMLDesignioCardElement;
        "designio-dropdown": HTMLDesignioDropdownElement;
        "designio-footer": HTMLDesignioFooterElement;
        "designio-input": HTMLDesignioInputElement;
        "designio-loader": HTMLDesignioLoaderElement;
        "designio-modal": HTMLDesignioModalElement;
        "designio-radio-button": HTMLDesignioRadioButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DesignioBadge {
        /**
          * Clases CSS adicionales (BOCC)
         */
        "classNames"?: string;
        /**
          * Identificador único para el badge/subcomponente
         */
        "idBadge"?: string;
        /**
          * Modo sólido (BBOG)
         */
        "isSolid"?: boolean;
        /**
          * Forma cuadrada (BOCC). Para BAVV use shape.
         */
        "isSquare"?: boolean;
        /**
          * Visibilidad del badge (BOCC). Si es false, no se muestra.
         */
        "isVisible"?: boolean;
        /**
          * Texto del badge (si no se usa el slot)
         */
        "label"?: string;
        /**
          * Evento emitido al interactuar con el badge
         */
        "onBadgeClicked"?: (event: DesignioBadgeCustomEvent<{
    type: 'bocc' | 'bpop' | 'bavv' | 'bbog';
    id?: string;
    label?: string;
  }>) => void;
        /**
          * Ícono de prefijo (soportado en bpop y bocc)
         */
        "prefixIcon"?: string;
        /**
          * Muestra botón de cierre (BBOG)
         */
        "removeTag"?: boolean;
        /**
          * Forma del borde (BAVV)
         */
        "shape"?: string;
        /**
          * Tamaño del badge (valores dependen del banco)
         */
        "size"?: string;
        /**
          * Ícono de sufijo (soportado en bpop)
         */
        "suffixIcon"?: string;
        /**
          * Tipo/entidad del badge que determina el adapter a renderizar
          * @default 'bbog'
         */
        "type"?: 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * Variante visual (mapeada por banco)
         */
        "variant"?: string;
    }
    interface DesignioButton {
        /**
          * The type of the button (for BAVV). BUTTON, SUBMIT, RESET.
          * @default 'submit'
         */
        "buttonType"?: 'button' | 'submit' | 'reset';
        /**
          * Custom height for the button (for BAVV).
         */
        "customHeight"?: string;
        /**
          * Custom width for the button (for BAVV).
         */
        "customWidth"?: string;
        /**
          * Enable divider between text and suffix icon for BOCC
          * @default false
         */
        "dividedBocc"?: boolean;
        /**
          * The html index of the button (for BAVV).
          * @default 0
         */
        "htmlIndex"?: number;
        /**
          * Id of button
         */
        "idButton"?: string;
        /**
          * State of button is Disabled true or false
          * @default false
         */
        "isDisabled"?: boolean;
        /**
          * State of button is Loading true or false
          * @default false
         */
        "isLoading"?: boolean;
        /**
          * Name or description of button
          * @default ''
         */
        "label"?: string;
        /**
          * The name of the button (for BAVV).
         */
        "name"?: string;
        /**
          * Event of Button
         */
        "onButtonClicked"?: (event: DesignioButtonCustomEvent<{
    type: string;
    id?: string;
    label?: string;
    value?: any;
  }>) => void;
        /**
          * Prop for load icon before name in button
         */
        "prefixIcon"?: string;
        /**
          * The size of the button (for BAVV). SMALL, REGULAR.
          * @default SIZE_BUTTON.REGULAR
         */
        "sizeBavv"?: SIZE_BUTTON;
        /**
          * Size for BOCC button (L, M, S)
          * @default 'M'
         */
        "sizeBocc"?: 'L' | 'M' | 'S';
        /**
          * Size for BPOP button
          * @default SIZE_BUTTON_BPOP.REGULAR
         */
        "sizeBpop"?: SIZE_BUTTON_BPOP;
        /**
          * Prop for load icon after name in button
         */
        "suffixIcon"?: string;
        /**
          * Type or entity form button
          * @default 'bbog'
         */
        "type"?: 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * Prop variant for bavv-design-button
          * @default 'primary'
         */
        "variantBavv"?: 'primary' | 'secondary' | 'tertiary' | 'borderless';
        /**
          * Type/variant for BOCC button - usando BdoButtonType correcto
          * @default 'primary'
         */
        "variantBocc"?: BdoButtonType;
        /**
          * Prop variant for bpop-design-button
          * @default VARIANT_BUTTON.PRIMARY
         */
        "variantBpop"?: VARIANT_BUTTON;
        /**
          * The width mode of the button (for BAVV). DEFAULT, AUTO, FULL.
          * @default WIDTH_MODE.DEFAULT
         */
        "widthModeBavv"?: WIDTH_MODE;
        /**
          * Width mode for BPOP button
          * @default WIDTH_MODE_BPOP.DEFAULT
         */
        "widthModeBpop"?: WIDTH_MODE_BPOP;
    }
    interface DesignioCard {
        /**
          * Text body of card
         */
        "bodyText"?: string;
        /**
          * type of border for card (BOCC only)
          * @default 'default'
         */
        "borderType"?: | 'default'
    | 'info'
    | 'success'
    | 'darger';
        /**
          * height of card (Only for BBOG)
         */
        "boxHeight"?: string;
        /**
          * width of card (Only for BBOG)
         */
        "boxWidth"?: string;
        /**
          * Text used for button (Only for BBOG)
          * @default ''
         */
        "buttonText"?: string;
        /**
          * Text used for secondary button (Only for BBOG card notification)
         */
        "buttonTextSecondary"?: string;
        /**
          * define if it's button or link (Only for BBOG)
          * @default 'link'
         */
        "buttonType"?: 'link' | 'secondary';
        /**
          * Border contain card, if false it does not show (BAVV only)
          * @default false
         */
        "cardHasBorder"?: boolean;
        /**
          * Padding of component, it can have 3 values: 12 | 24 | 36 (BAVV only)
          * @default 12
         */
        "cardPadding"?: PaddingForCard;
        /**
          * Type of card for BBOG
          * @default 'access'
         */
        "cardType"?: 'access' | 'notification';
        /**
          * define color for text in avatar (Only for BBOG)
         */
        "colorTextAvatar"?: string;
        /**
          * enable footer of card (BOCC only)
          * @default false
         */
        "displayFooter"?: boolean;
        /**
          * enable header of card (BOCC only)
          * @default false
         */
        "displayHeader"?: boolean;
        /**
          * enable or disable component (Only for BBOG access) and used for badge in avatar (Only for BBOG notification)
         */
        "enable"?: boolean;
        /**
          * Text used for footer (only BOCC)
         */
        "footerText"?: string;
        /**
          * define if it's button or link for access card in true for button, in notification define if has two buttons (Only for BBOG)
          * @default false
         */
        "hasButtons"?: boolean;
        /**
          * Text used for header (only BOCC)
         */
        "headerText"?: string;
        /**
          * Id of card
         */
        "idCard"?: string;
        /**
          * id of footer (BOCC only)
         */
        "idFooter"?: string;
        /**
          * id of header (BOCC only)
         */
        "idHeader"?: string;
        /**
          * define tag solid or with border (Only for BBOG)
          * @default false
         */
        "isTagSolid"?: boolean;
        /**
          * Event emitted when the card is clicked (Only for BBOG)
         */
        "onCardClicked"?: (event: DesignioCardCustomEvent<void>) => void;
        /**
          * Event emitted for button or link (Only for BBOG)
         */
        "onLinkClicked"?: (event: DesignioCardCustomEvent<void>) => void;
        /**
          * Event emitted for secondary button (Only for BBOG)
         */
        "onLinkClickedSecond"?: (event: DesignioCardCustomEvent<void>) => void;
        /**
          * Event emitted for options menu (Only for BBOG)
         */
        "onOptionMenuClicked"?: (event: DesignioCardCustomEvent<void>) => void;
        /**
          * Text secondary  of card (only BBOG)
         */
        "secondaryText"?: string;
        /**
          * Text used for tag (Only for BBOG)
         */
        "tagLabel"?: string;
        /**
          * text for avatar (Only for BBOG)
         */
        "textAvatar"?: string;
        /**
          * define title for card (Only for BBOG)
          * @default ''
         */
        "titleCard"?: string;
        /**
          * define title in one line or two (Only for BBOG)
         */
        "titleHasOneLine"?: boolean;
        /**
          * Type or entity form buttom
          * @default 'bocc'
         */
        "type"?: 'bocc' | 'bavv' | 'bbog' | 'bpop';
        /**
          * define avatar type (Only for BBOG)
          * @default 'icon'
         */
        "typeAvatar"?: 'text' | 'icon' | 'img';
        /**
          * define type icon (Only for BBOG)
         */
        "typeIcon"?: string;
        /**
          * Type of logo for access card (Only for BBOG)
         */
        "typeLogo"?: string;
        /**
          * define type for pictogram (Only for BBOG)
         */
        "typePicto"?: string;
        /**
          * define type tag (Only for BBOG)
         */
        "typeTag"?: string;
        /**
          * define state of card (Only for BBOG)
          * @default false
         */
        "unread"?: boolean;
        /**
          * link for image of avatar (Only for BBOG)
         */
        "urlImgAvatar"?: string;
        /**
          * options for card in bbog (Only for BBOG)
         */
        "userOptions"?: string;
    }
    interface DesignioDropdown {
        /**
          * Helper Text
         */
        "helperText"?: string;
        /**
          * Disabled dropdown
          * @default false
         */
        "isDisabled"?: boolean;
        /**
          * Text Help Bog
          * @default false
         */
        "isHelp"?: boolean;
        /**
          * Popup Mode mobile
          * @default false
         */
        "isPopUp"?: boolean;
        /**
          * Required
          * @default false
         */
        "isRequired"?: boolean;
        /**
          * Label dropdown
         */
        "label"?: string;
        /**
          * Event emit to select
         */
        "onDesignioSelectionChange"?: (event: DesignioDropdownCustomEvent<any>) => void;
        /**
          * Options List
          * @default []
         */
        "options"?: any[];
        /**
          * Placeholder
         */
        "placeholder"?: string;
        /**
          * Size dropdown
         */
        "size"?: SizeDropDown;
        /**
          * State dropdown (error, warning, default, selected...)
         */
        "state"?: StateDropDown;
        /**
          * Tooltip enable (Bogotá only)
          * @default false
         */
        "tooltip"?: boolean;
        /**
          * Tooltip header text
         */
        "tooltipHeader"?: string;
        /**
          * Tooltip body text
         */
        "tooltipMessage"?: string;
        /**
          * Label dropdown
          * @default 'bbog'
         */
        "type"?: 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * Select Value
         */
        "value"?: string | number;
    }
    interface DesignioFooter {
        /**
          * additionalText
          * @default 'Texto adicional'
         */
        "additionalText"?: string;
        /**
          * Props BOCC
          * @default 'bdo-footer-company'
         */
        "elementId"?: string;
        /**
          * showAdditionalText
          * @default false
         */
        "showAdditionalText"?: boolean;
        /**
          * showFogafinLogo
          * @default false
         */
        "showFogafinLogo"?: boolean;
        /**
          * Bank footer
          * @default 'bocc'
         */
        "type"?: 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * Props commons
          * @default FooterDesignioVariant.DEFAULT
         */
        "variant"?: FooterDesignioVariant;
    }
    interface DesignioInput {
        /**
          * The autocomplete attribute.
          * @default 'off'
         */
        "autocomplete"?: string;
        /**
          * Optional button text to display on the right side of the input for BAVV.
          * @default ''
         */
        "bavvButtonText"?: string;
        /**
          * The icon name for the input of BAVV.
          * @default ''
         */
        "bavvIconName"?: string;
        /**
          * The icon position for the input of BAVV.
          * @default ''
         */
        "bavvIconPosition"?: 'left' | 'right' | '';
        /**
          * Autoselect of BBOG.
          * @default false
         */
        "bbogAutoSelect"?: boolean;
        /**
          * The decimal quantity of BBOG.
         */
        "bbogDecimalQuantity"?: number;
        /**
          * Email validation on blur of BBOG.
          * @default false
         */
        "bbogEmailValidationOnBlur"?: boolean;
        /**
          * Name of the icon to render of BBOG.
          * @default ''
         */
        "bbogIcon"?: string;
        /**
          * The interactive tooltip message of BBOG
         */
        "bbogInteractiveTooltipMessage"?: string;
        /**
          * Name of the left icon to render of BBOG.
         */
        "bbogLeftIcon"?: string;
        /**
          * Enables/Disables the hide password mode.
          * @default false
         */
        "bbogPasswordMode"?: boolean;
        /**
          * Enables/Disables the control of BBOG.
          * @default 'ENABLED'
         */
        "bbogStatus"?: string;
        /**
          * Show/Hide tooltip of BBOG.
          * @default false
         */
        "bbogTooltip"?: boolean;
        /**
          * The tooltip message of BBOG
         */
        "bbogTooltipMessage"?: string;
        /**
          * The tooltip position of BBOG
          * @default 'right'
         */
        "bbogTooltipPosition"?: string;
        /**
          * The tooltip title of BBOG
         */
        "bbogTooltipTitle"?: string;
        /**
          * View mode of BBOG.
          * @default false
         */
        "bbogViewMode"?: boolean;
        /**
          * The attributes of the input field of BOCC
         */
        "boccAttributes"?: BoccInput | string;
        /**
          * The field status of the input field of BOCC
         */
        "boccFieldStatus"?: FIELD_STATUS | string;
        /**
          * The maximum number of decimals allowed of BOCC
          * @default 0
         */
        "boccMaximumDecimalsAllowed"?: number;
        /**
          * The prefix text of the input field of BOCC
          * @default ''
         */
        "boccPrefixText"?: string;
        /**
          * IDs to describe via `aria-describedby` of BPOP.
          * @default ''
         */
        "bpopAriaDescribedBy"?: string;
        /**
          * Aria label for the input of BPOP.
          * @default ''
         */
        "bpopAriaLabelProp"?: string;
        /**
          * Input `autocapitalize` attribute of BPOP.
          * @default ''
         */
        "bpopAutocapitalizeProp"?: string;
        /**
          * Text of the embedded button (right side) of BPOP.
          * @default ''
         */
        "bpopButtonText"?: string;
        /**
          * Name of the icon to render of BPOP.
          * @default ''
         */
        "bpopIconName"?: string;
        /**
          * Icon position (`left`/`right`) of BPOP.
          * @default ''
         */
        "bpopIconPosition"?: 'left' | 'right' | '';
        /**
          * HTML `size` attribute of BPOP.
         */
        "bpopSize"?: number;
        /**
          * HTML `spellcheck` attribute of BPOP.
          * @default false
         */
        "bpopSpellcheckProp"?: boolean;
        /**
          * Step size (number/date) of BPOP.
         */
        "bpopStepSize"?: string | number;
        /**
          * `tabindex` to apply of BPOP.
         */
        "bpopTabIndexProp"?: number;
        /**
          * HTML `title` attribute of BPOP.
          * @default ''
         */
        "bpopTitleProp"?: string;
        /**
          * Whether the input is disabled for BAVV, BPOP or BOCC. It doesn't apply to BBOG. For BBOG please use the bbogStatus property
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Entity for the input
          * @default 'bbog'
         */
        "entity"?: 'bocc' | 'bpop' | 'bavv' | 'bbog';
        /**
          * The text shown as helper below the input for BAVV, BPOP or BBOG. It doesn't apply to BOCC.
         */
        "helper"?: string;
        /**
          * The ID attribute of the input.
          * @default ''
         */
        "idProp"?: string;
        /**
          * The input mode (e.g., numeric, text) for BAVV, BPOP or BOCC. It doesn't apply to BBOG.
         */
        "inputModeProp"?: string;
        /**
          * Label text displayed with the input field.
          * @default ''
         */
        "label"?: string;
        /**
          * The maximum value (for number/date inputs).
         */
        "max"?: string | number;
        /**
          * The maxlength attribute defining max number of characters.
         */
        "maxLength"?: number;
        /**
          * The minimum value (for number/date inputs).
         */
        "min"?: string | number;
        /**
          * The minlength attribute defining min number of characters.
         */
        "minLength"?: number;
        /**
          * The name attribute of the input.
          * @default ''
         */
        "name"?: string;
        /**
          * Emitted when the user clicks on BAVV button.
         */
        "onBavvButtonClick"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when the BAVV input loses focus on.
         */
        "onBavvInputBlur"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when the BAVV input changes.
         */
        "onBavvInputChange"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when the BAVV input gets focus on.
         */
        "onBavvInputFocus"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when the BAVV input value changes.
         */
        "onBavvValueChange"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when the user input of BBOG changes.
         */
        "onBbogAtInputChanged"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when the user enters the enter key on BBOG input.
         */
        "onBbogAtInputEnterKey"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when it looses focus on BBOG input.
         */
        "onBbogAtInputOnBlur"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when it gains focus on BBOG input.
         */
        "onBbogAtInputOnFocus"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when the user enters any key down on BBOG input.
         */
        "onBbogAtInputOnKeyDown"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when the user input of BBOG is updated.
         */
        "onBbogAtInputUpdated"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * Emitted when the user clicks on the input icon of BBOG.
         */
        "onBbogOnInputIconClick"?: (event: DesignioInputCustomEvent<void>) => void;
        /**
          * The pattern attribute for regex validation.
         */
        "pattern"?: string;
        /**
          * The placeholder text displayed when the input is empty.
          * @default ''
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required.
          * @default false
         */
        "required"?: boolean;
        /**
          * The type of input (e.g., text, password, email, number, etc.).
          * @default DesignioInputType.Text
         */
        "type"?: DesignioInputType;
        /**
          * The value of the input.
          * @default ''
         */
        "value"?: string;
    }
    interface DesignioLoader {
        /**
          * Starts animation as soon as component is loaded (BBOG)
         */
        "autoPlay"?: boolean;
        /**
          * Displays a message when loader is open (BOCC)
         */
        "displayMessage"?: boolean;
        /**
          * External json file for animation (BBOG)
         */
        "fileAnimation"?: string;
        /**
          * Id for loader element (BBOG)
         */
        "idEl"?: string;
        /**
          * Variant for BAVV loader
         */
        "isMainSpinner"?: boolean;
        /**
          * Makes loader visible or hidden
         */
        "isopen"?: boolean;
        /**
          * Loader type (BBOG)
         */
        "loaderType"?: string;
        /**
          * Plays animation in a loop (BBOG)
         */
        "loop"?: boolean;
        /**
          * Main text for loader (BOCC, BAVV, BBOG, BPOP)
         */
        "mainText"?: string;
        /**
          * Secondary text for loader, if available (BOCC, BAVV)
         */
        "secondaryText"?: string;
        /**
          * Loader size (BPOP)
         */
        "size"?: | 'xsmall'
    | 'small'
    | 'medium'
    | 'large';
        /**
          * Type or entity form buttom
          * @default 'bbog'
         */
        "type"?: 'bocc' | 'bpop' | 'bavv' | 'bbog';
    }
    interface DesignioModal {
        /**
          * Title alignment.
          * @default 'center'
         */
        "alignTitle"?: 'left' | 'center' | 'right';
        /**
          * Custom CSS class for the modal.
         */
        "customClass"?: string;
        /**
          * Direction of the modal buttons.
          * @default 'vertical'
         */
        "direction"?: 'horizontal' | 'vertical';
        /**
          * Optional element id for the modal.
         */
        "elementId"?: string;
        /**
          * Hide close button in the modal.
          * @default false
         */
        "hideClose"?: boolean;
        /**
          * Icon name for the modal.
         */
        "icon"?: string;
        /**
          * Illustrated icon name for the modal.
         */
        "illustratedIcon"?: string;
        /**
          * Custom modal ID.
         */
        "modalId"?: string;
        /**
          * Title of the modal.
         */
        "modalTitle"?: string;
        /**
          * Event emitted when the modal is closed.
         */
        "onClosed"?: (event: DesignioModalCustomEvent<{ type: string; modalId: string }>) => void;
        /**
          * Event emitted when the modal is opened.
         */
        "onOpened"?: (event: DesignioModalCustomEvent<{ type: string; modalId: string }>) => void;
        /**
          * Primary button configuration.
         */
        "primaryButtonConfig"?: BdoButtonStandard;
        /**
          * Secondary button configuration.
         */
        "secondaryButtonConfig"?: BdoButtonStandard;
        /**
          * Show close button in the modal.
          * @default false
         */
        "showClose"?: boolean;
        /**
          * Show primary button in the modal.
          * @default false
         */
        "showPrimaryButton"?: boolean;
        /**
          * Show secondary button in the modal.
          * @default false
         */
        "showSecondaryButton"?: boolean;
        /**
          * Size of the modal.
          * @default 'md'
         */
        "size"?: 'lg' | 'md' | 'sm';
        /**
          * Subtitle of the modal.
         */
        "subtitle"?: string;
        /**
          * Modal type to display.
          * @default 'bbog'
         */
        "type"?: 'bocc' | 'bpop' | 'bavv' | 'bbog';
    }
    interface DesignioRadioButton {
        /**
          * Allow unselecting the radio button.
          * @default false
         */
        "allowUnselect"?: boolean;
        /**
          * Whether the radio button is checked.
          * @default false
         */
        "checked"?: boolean;
        /**
          * Whether to wrap the radio in a container.
          * @default false
         */
        "container"?: boolean;
        /**
          * Custom attributes for the radio button.
         */
        "customAttributes"?: RadioButtonAttributes | string;
        /**
          * Whether the radio button is disabled.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Whether to invert the label position.
          * @default false
         */
        "invertLabel"?: boolean;
        /**
          * The label for the radio button.
         */
        "label"?: string;
        /**
          * The group name for the radio button.
         */
        "name"?: string;
        /**
          * Emitted when the radio button changes.
         */
        "onRadioChange"?: (event: DesignioRadioButtonCustomEvent<RadioButtonChangeDetail>) => void;
        /**
          * The unique id for the radio button.
         */
        "radioId"?: string;
        /**
          * Show the label next to the radio button.
          * @default true
         */
        "showLabel"?: boolean;
        /**
          * The size of the radio button.
          * @default 'default'
         */
        "size"?: 'default' | 'large' | 'medium' | 'small';
        /**
          * The visual state of the radio button.
          * @default 'default'
         */
        "state"?: | 'default'
    | 'hover'
    | 'error'
    | 'info'
    | 'disabled'
    | 'checked';
        /**
          * The type of radio button (design system).
          * @default 'bpop'
         */
        "type"?: 'bpop' | 'bavv' | 'bbog' | 'bocc';
        /**
          * The value of the radio button.
         */
        "value"?: string;
    }
    interface MyComponent {
        /**
          * Name
         */
        "name"?: string;
    }
    interface IntrinsicElements {
        "designio-badge": DesignioBadge;
        "designio-button": DesignioButton;
        "designio-card": DesignioCard;
        "designio-dropdown": DesignioDropdown;
        "designio-footer": DesignioFooter;
        "designio-input": DesignioInput;
        "designio-loader": DesignioLoader;
        "designio-modal": DesignioModal;
        "designio-radio-button": DesignioRadioButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "designio-badge": LocalJSX.DesignioBadge & JSXBase.HTMLAttributes<HTMLDesignioBadgeElement>;
            "designio-button": LocalJSX.DesignioButton & JSXBase.HTMLAttributes<HTMLDesignioButtonElement>;
            "designio-card": LocalJSX.DesignioCard & JSXBase.HTMLAttributes<HTMLDesignioCardElement>;
            "designio-dropdown": LocalJSX.DesignioDropdown & JSXBase.HTMLAttributes<HTMLDesignioDropdownElement>;
            "designio-footer": LocalJSX.DesignioFooter & JSXBase.HTMLAttributes<HTMLDesignioFooterElement>;
            "designio-input": LocalJSX.DesignioInput & JSXBase.HTMLAttributes<HTMLDesignioInputElement>;
            "designio-loader": LocalJSX.DesignioLoader & JSXBase.HTMLAttributes<HTMLDesignioLoaderElement>;
            "designio-modal": LocalJSX.DesignioModal & JSXBase.HTMLAttributes<HTMLDesignioModalElement>;
            "designio-radio-button": LocalJSX.DesignioRadioButton & JSXBase.HTMLAttributes<HTMLDesignioRadioButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
